# Don't print a new line at the start of the prompt
add_newline = false

# Use custom format
format = """\
╭─$username$hostname $directory( $env_var)( $kubernetes)( $nodejs)( $java)( $git_branch$git_status)
└─$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[\\$](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
#format = "[](green)[ $path$read_only ]($style)[](green)"
truncation_symbol = "…/"
style = "bold green"
#style = "bg:green bold fg:white"

[kubernetes]
format = '[<󰠳 $context \($namespace\)>]($style)'
style = "cyan"
disabled = false
[kubernetes.context_aliases]
"sl-dev" = "sl-dev"
"sl-cons" = "sl-cons"
"sl-test" = "sl-test"
"sl-prod" = "SL-PROD"
"sl-aws-prod" = "SL-AWS-PROD"

[gcloud]
disabled = true

[hostname]
ssh_only = false
format =  "[@$hostname](bold blue) "
trim_at = "."
disabled = false

[username]
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = true

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "yellow"
truncation_length = 40
truncation_symbol = "…"

[git_status]
format = '([:\[($diverged )($conflicted )($stashed)($deleted )($renamed)($modified )($staged )($untracked)\]]($style))'
conflicted = " "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = ""
stashed = ""
modified = " "
staged = '[++\($count\)](green) '
renamed = ""
deleted = "✘ "
style = "yellow"

[nodejs]
format = "[$symbol$version]($style)"
symbol = "󰎙 "
style = "bold green"

[java]
format = "[$symbol$version]($style)"
symbol = " "
style = "fg:#bf5700"

[env_var]
variable = "HTTPS_PROXY"
format = "[($symbol $env_value)]($style)"
default = " "
symbol = " "
style = "red"
disabled = true